definitions:
  models.Config:
    properties:
      access_token:
        type: string
      athlete_id:
        type: integer
      client_id:
        type: string
      client_secret:
        type: string
      created_at:
        type: string
      id:
        type: integer
      updated_at:
        type: string
    type: object
  models.ConfigInput:
    properties:
      access_token:
        type: string
      athlete_id:
        type: integer
      client_id:
        type: string
      client_secret:
        type: string
    type: object
info:
  contact: {}
paths:
  /config:
    get:
      consumes:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Config'
      summary: Get Application Config
      tags:
      - config
    put:
      consumes:
      - application/json
      parameters:
      - description: Config Input
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/models.ConfigInput'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ConfigInput'
      summary: Upsert Application Config
      tags:
      - config
swagger: "2.0"
